services:
  core-db:
    image: postgres:15-alpine
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_LOCAL_PORT}:5432"
    volumes:
      - pgdata_core:/var/lib/postgresql/data

  ml-db:
    image: postgres:15-alpine
    env_file: ../.env
    environment:
      POSTGRES_USER: ${ML_DB_USER}
      POSTGRES_PASSWORD: ${ML_DB_PASSWORD}
      POSTGRES_DB: ${ML_DB_NAME}
    ports:
      - "${ML_DB_LOCAL_PORT}:5432"
    volumes:
      - pgdata_ml:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: ../.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    env_file: ../.env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}); do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME} || true;
      /usr/bin/mc anonymous set download myminio/${MINIO_BUCKET_NAME};
      exit 0;
      "

  core-api:
    build:
      context: ..
      dockerfile: deploy/core.Dockerfile
    ports:
      - "${HTTP_PORT}:8080"
    env_file: ../.env
    environment:
      DB_HOST: core-db
      DB_PORT: 5432
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ../.env:/root/.env:ro
    depends_on:
      - core-db
      - redis
      - rabbitmq

  ml-worker:
    build:
      context: ..
      dockerfile: deploy/ml.Dockerfile
    env_file: ../.env
    environment:
      ML_DB_HOST: ml-db
      ML_DB_PORT: 5432
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MINIO_ENDPOINT: minio:9000
    volumes:
      - ../.env:/root/.env:ro
    depends_on:
      - ml-db
      - rabbitmq
      - minio-init

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ../../plotty_frontend:/app
      - /app/node_modules
      - /app/.next
    env_file: ../.env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_API_MOCKING: ${NEXT_PUBLIC_API_MOCKING}
      HOST: 0.0.0.0
    depends_on:
      - core-api

volumes:
  pgdata_core:
  pgdata_ml:
  minio_data: