name: Deploy Backend

on:
  push:
    branches: ["main", "deploy"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Core API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/core.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/plotty-core:latest

      - name: Build and push ML Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/ml.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/plotty-ml:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # ШАГ 1: Копируем файл
      - name: Copy docker-compose file via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "deploy/docker-compose.prod.yml"
          target: "/home/ubuntu/plotty"

      # ШАГ 2: Запускаем
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Переходим в папку, где лежит скопированный файл
            cd /home/ubuntu/plotty/deploy

            # Если файла .env нет в папке deploy, копируем его из родительской папки
            # (так как мы создали его вручную в /home/ubuntu/plotty)
            cp /home/ubuntu/plotty/.env .

            touch acme.json && chmod 600 acme.json

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f
